export const body: string;
export const button: string;
export const primary: string;
export const secondary: string;
export const normal: string;
export const pointer: string;
export const controls: string;
export const speedSlider: string;
export const speedValue: string;
